version: '3.4'

services:
  catalog.db:
        container_name: catalogdb
        image: postgres
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
            - POSTGRES_DB=CatalogDb
        ports:
            - 5432:5432
        volumes:
            - postgres_catalog:/var/lib/postgresql/data
