version: '3.4'

services:
  catalog.db:
    container_name: catalogdb
    image: postgres
    environment:
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=postgres
        - POSTGRES_DB=CatalogDb
    restart: always
    volumes:
        - postgres_catalog:/var/lib/postgresql/data
    ports:
        - 5432:5432

